### ISSUE TITLE
add user list

### ISSUE THREAD

**Issue by strukturart** [R3D2/kirby3-newsletter#1]
Hello,

thanks for developing the plugin, i would like to change the recipient list so that the newsletters are sent to all users. is it correct that I have to change this here: https://github.com/R3D2/kirby3-newsletter/blob/d7401ac2259f8ea8ffc6a4c6e1beb481c9813724/lib/newsletter.php#L10
?

**Comment by R3D2** [comment]
Yep !

**Comment by strukturart** [comment]
```
  public static function getSubscribers()
    {
        $to = [];

        // Set the uri of your subscriber blueprint in the page function
        /*
        foreach (kirby()->page('abonnes')->subscriber()->toStructure() as $e) {
            $to[] = $e->email()->toString();
        }
        */

        
		$users = $kirby->users()->filterBy('role','admin');
		$to[] = $users->pluck('email')->toString();
		
        return $to;
    }
```

**Comment by R3D2** [comment]
public static function getSubscribers()
    {
        $to = [];

        // Set the uri of your subscriber blueprint in the page function
        /*
        foreach (kirby()->page('abonnes')->subscriber()->toStructure() as $e) {
            $to[] = $e->email()->toString();
        }
        */

        
		$users = $kirby->users()->filterBy('role','admin');
		$to = $users->pluck('email')->toArray();
		
        return $to;
    }

**Comment by strukturart** [comment]
if you are sure about `toArray ()`,` pluck () `does not make an array out of the list
```
$users = $kirby->users()->filterBy('role','admin');
			$to = $users->pluck('email');
			
			echo print_r($to);
```

**Comment by R3D2** [comment]
Actually, you are right, it already output an array, so you dont need to "toArray" it.

```
$to = $users->pluck('email');
```

[doc](https://getkirby.com/docs/reference/objects/users/pluck)

**Comment by strukturart** [comment]
Are you sure with ->toString()

because I get an error message when I test it in a template:

```
<?php
	$users = $kirby->users()->filterBy('role','test');
	$to = $users->pluck('email')->toString();

	dump($to);
	?>
```

**error output**

`Call to a member function toString() on array`

**Comment by R3D2** [comment]
I don't have access to a computer right now, but I hope I will be able to check on this in 2hours~

**Comment by strukturart** [comment]
https://github.com/strukturart/kirby3-newsletter/blob/1f4c613251dd5171b97d36d558bff76168ee5694/lib/newsletter.php#L55
